// First Post
const A = "https://images.craigslist.org/00P0P_jHZllMUA5h6_0CI0t2_600x450.jpg";
const B = "https://images.craigslist.org/00M0M_jHt1JGRUXgl_0CI0t2_600x450.jpg";
const C = "https://images.craigslist.org/00808_fZWTwccKWRH_0CI0t2_600x450.jpg";
const D = "https://images.craigslist.org/00L0L_bEec2wpBJPn_0CI0pd_600x450.jpg";

// const img_arry_a = [A, B, C, D, E];

exports.examplePosts = [
  {
    username: "BluesFan",
    email: "Asmongo@battlenet.com",
    phone: "999-999-9999",
    zip: "32003",
    type: "Selling Gear",
    equipment: "Guitar",
    title: "1945 Rickenbacher Electro Lap Steel Guitar",
    body: "Selling 1945 Rickenbacher Electro Lap Steel Guitar used/vintage. Bought it in Japan.",
    price: 1400,
    images: [A, B, C, D],
  },
  {
    username: "Serg51",
    email: "sergioBalos@gmail.com",
    phone: "9855648196",
    zip: "32044",
    type: "Buying Gear",
    equipment: "Bass",
    title: "I want buy a fender jazz bass",
    body: "Hey guys, I am interested in buying any jazz bass circa -80's to modern's. 4 string basses only. I have $1300.00 to spend",
    price: 1300,
    images: [
      "https://images.craigslist.org/00s0s_e7iv0S7mzX5_0lM0t2_600x450.jpg",
      "https://images.craigslist.org/00p0p_fqHWvHTK9lr_0lM0t2_600x450.jpg",
      "https://images.craigslist.org/01313_1jsoxdQsRQs_0lM0t2_600x450.jpg",
    ],
  },

  {
    username: "Razzys",
    email: "RazMgmt@razzyproductions.com",
    phone: "7779978456",
    zip: "33863",
    type: "Selling Gear",
    equipment: "Drums",
    title: "Selling Pearl S1330 piccolo Snare",
    body: "Selling Pearl S1330 piccolo Snare. It has a new drum head and sounds tight. Used but looks brand new. Asking for $288.00 but can be negotiated. No trades. Cash only.",
    price: 288,
    images: [
      "https://images.craigslist.org/00a0a_87ZTDoX5sn3_11O0Co_600x450.jpg",
      "https://images.craigslist.org/00Q0Q_2aPmT96m5l2_0Mo12w_600x450.jpg",
    ],
  },

  {
    username: "Mariol33t",
    email: "mariomario@Nitendo.jp",
    phone: "9584531524",
    zip: "32056",
    type: "Selling Gear",
    equipment: "Studio Equipment",
    title: "Selling UAD Microphone preamp",
    body: "Barely used UAD 4107D. Bought it for a project but I don't need it. Practically brand new and powered on only once. Will include original box and packaging. Will sell for $1500. No trades and price is firm.",
    price: 1500,
    images: [
      "https://i.ebayimg.com/images/g/baMAAOSwzAVnVbg0/s-l1600.webp",
      "https://i.ebayimg.com/images/g/jBAAAOSwtKNnVbg0/s-l960.webp",
      "https://i.ebayimg.com/images/g/JtEAAOSwh1NnVbg0/s-l960.webp",
      "https://i.ebayimg.com/images/g/USoAAOSwLndnVbg0/s-l960.webp",
    ],
  },
  {
    username: "AvsFan44",
    email: "butler23@hotmail.com",
    phone: "7894162154",
    zip: "32511",
    type: "Selling Gear",
    equipment: "Brass",
    title: "Student Concord Alto Sax",
    body: "Bought this for my son for school. Recently serviced and clean. This guy costed me $375.00 brand new. I am looking for $275.00 Will go lower if it makes sense. Cash / paypal only.",
    price: 275,
    images: [
      "https://images.craigslist.org/00b0b_eGvG4UpwmDX_08R0k9_600x450.jpg",
      "https://images.craigslist.org/00X0X_239iZMuaAng_0fu0kE_600x450.jpg",
      "https://images.craigslist.org/01313_haqLch8radr_0bz0kl_600x450.jpg",
      "https://images.craigslist.org/00L0L_auxadVsOqFl_0kE0fu_600x450.jpg",
      "https://images.craigslist.org/00P0P_dlxCnVLxg4D_0kE0fu_600x450.jpg",
    ],
  },
  {
    username: "JaxStudios",
    email: "jaxstudios999@gmail.com",
    phone: "9584531524",
    zip: "32326",
    type: "Buying Gear",
    equipment: "Microphones",
    title: "Looking to buy a Shure SM58",
    body: "Hey guys! Jax studios is looking to bolster our mic locker! We are on the lookout for a Shure SM58 microphone. We are willing to negotiate a price! ",
    price: 100,
    images: [
      "https://images.craigslist.org/00d0d_2aneKqgq05G_0nN0t2_600x450.jpg",
    ],
  },
  // {
  //     username: 'Bobocolopous14',
  //     email: "N/A",
  //     phone: "N/A",
  //     zip: "34219",
  //     type: "Selling Gear",
  //     equipment: "Woodwind",
  //     title: "Bamboo Flute ready for new owner",
  //     body: "Bought it in Malaysia. Cleaned throughly. Made from bamboo and stained brown, looks beautiful. Looking for $400.00 cash/cash app/paypal. Contact me only through my Maestroboard profile. Thanks!",
  //     price: 400,
  //     images: [12, 13, 14, 15],
  // },
  // {
  //     username: 'GuitarFreak198',
  //     email: "JGuitar297@yahoo.com",
  //     phone: "N/A",
  //     zip: "32668",
  //     type: "Selling Gear",
  //     equipment: "Guitar",
  //     title: "1998 Fender Stratocaster H/S/S.",
  //     body: "Used/Relic Fender Stratocaster up for sale. Low frets, no buzzing, tunes perfectly and like a beauty. She has some road miles to her but shes ready for a new home. $785.00 cash First one to take it, takes it.",
  //     price: 785,
  //     images: [12, 13, 14, 15],
  // },
  // {
  //     username: 'Korn2Freak',
  //     email: "Korn2Freak@gmail.com",
  //     phone: "N/A",
  //     zip: "32639",
  //     type: "Selling Gear",
  //     equipment: "Bass",
  //     title: "2002 5 String Black Warwick Thumb bass.",
  //     body: "Hey guys, currently selling my 2002 5 string Warwick Thumb bass. Kept in a smoke free house. Works perfectly. Comes with a hard case. $900.00. Check out my other posts for a bass amp FS.",
  //     price: 900,
  //     images: [12, 13, 14, 15],
  // },
  // {
  //     username: 'Korn2Freak',
  //     email: "Korn2Freak@gmail.com",
  //     phone: "N/A",
  //     zip: "32639",
  //     type: "Selling Gear",
  //     equipment: "Amp",
  //     title: "Ampeg FS200 Combo Amp",
  //     body: "Hey guys, selling my Ampeg FS200 Combo amp.Speakers are not blown and amp works perfectly. Really loud and has good EQ. Low and highs shine. $675.00 and it's yours!",
  //     price: 900,
  //     images: [12, 13, 14, 15],
  // },
  // {
  //     username: 'JaxStudios',
  //     email: "jaxstudios999@gmail.com",
  //     phone: "9584531524",
  //     zip: "32326",
  //     type: "Buying Gear",
  //     equipment: "Studio Equipment",
  //     title: "Looking to buy any microphone preamp!",
  //     body: "Hey guys! Jax studios is looking to bolster our studio equipment! We are on the lookout for any microphone preamp (top tier perferable). UAD and Great River Electronics would be great! We have $1500 budget!",
  //     price: 1500,
  //     images: [12, 13, 14, 15],
  // },
];
