exports.exampleUsers = [
  {
    username: "Asmongo22",
    password: "981249824",
    email: "amsongo22@gmail.com",
    profileImg: "img.png",
    address1: "Five Square Tower",
    address2: "1762-02 NW 317th Ave",
    zipcode: "2009E73",
    city: "2009E73",
    state: "2009E73",
    country: "United States",
    phoneNumber: "08645897755",
    altPhoneNumber: "091286421",
  },
  {
    username: "Serg51",
    email: "sergioBalos@gmail.com",
    phone: "9855648196",
    zip: "32044",
    type: "Buying Gear",
    equipment: "Bass",
    title: "I want buy a vintage fender jazz bass",
    body: "Hey guys, I am interested in buying any vintage jazz bass circa -60's to 90's. 4 string basses only. I have $1300.00 to spend",
    price: 1400,
    images: [4, 5, 6, 7],
  },

  {
    username: "Razzys",
    email: "RazMgmt@razzyproductions.com",
    phone: "7779978456",
    zip: "33863",
    type: "Selling Gear",
    equipment: "Drums",
    title: "Selling Pearl piccolo Snare",
    body: "Selling Pearl piccolo Snare. It has a new drum head and sounds tight. Used but looks brand new. Asking for $288.00 but can be negotiated. No trades. Cash only.",
    price: 288,
    images: [8, 9, 10, 11],
  },

  {
    username: "Mariol33t",
    email: "mariomario@Nitendo.jp",
    phone: "9584531524",
    zip: "32056",
    type: "Selling Gear",
    equipment: "Studio Equipment",
    title: "Selling UAD Microphone preamp",
    body: "Barely used UAD 4107D. Bought it for a project but I don't need it. Practically brand new and powered on only once. Will include original box and packaging. Will sell for $1500. No trades and price is firm.",
    price: 1500,
    images: [12, 13, 14, 15],
  },
  {
    username: "AvsFan44",
    email: "butler23@hotmail.com",
    phone: "7894162154",
    zip: "32511",
    type: "Selling Gear",
    equipment: "Brass",
    title: "Student Concord Alto Sax",
    body: "Bought this for my son for school. Recently serviced and clean. This guy costed me $375.00 brand new. I am looking for $275.00 Will go lower if it makes sense. Cash / paypal only.",
    price: 275,
    images: [12, 13, 14, 15],
  },
];
